In [2]:
import numpy as np

In [5]:
my_list = [1,2,3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [8]:
my_mat = [[1,2],[3,4],[5,6]]

In [9]:
np.array(my_mat)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr1 = np.array(my_mat)
print(arr1)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
#creating an array using numpy 
#format (start,upto, step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.36786721, 0.6687785 , 0.75807204, 0.56121707, 0.49012298])

In [19]:
np.random.rand(4,3)

array([[0.54217186, 0.709374  , 0.14197136],
       [0.20910782, 0.02224668, 0.14446399],
       [0.25904101, 0.65640882, 0.08922722],
       [0.4060056 , 0.19665537, 0.88241973]])

In [20]:
np.random.rand(2)

array([0.44355052, 0.54398329])

In [41]:
np.random.randint(4,16,4)

array([11, 13, 12, 14])

In [44]:
arry = np.arange(25)
print(arry)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [45]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arry.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr = np.random.randint(0,100,15)
ranarr

array([97, 91, 65, 98, 34, 40, 13, 62, 52, 48, 38, 80, 22, 49, 20])

In [53]:
ranarr.max()

98

In [54]:
ranarr.min()

13

In [55]:
ranarr.argmax()

3

In [57]:
ranarr.shape

(15,)

In [62]:
ranarr.reshape(3,5)

array([[97, 91, 65, 98, 34],
       [40, 13, 62, 52, 48],
       [38, 80, 22, 49, 20]])

In [63]:
ranarr.dtype

dtype('int64')

In [3]:
arr = np.arange(11)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
#numpy arrayys differ from normal lists in the way that numpy arrays can boradcast
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr #refers to the original array and does not make a copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy [:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [27]:
arr_2d[0][0]

10

In [28]:
arr_2d[0,0]

10

In [31]:
arr_2d[:,:1]

array([[10],
       [40],
       [70]])

In [32]:
arr>5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [33]:
arr = np.arange(10)

In [34]:
#conditional statements
bool_arr = arr>5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [35]:
arr[arr>5]

array([6, 7, 8, 9])

In [36]:
arr_2d = np.arange(36).reshape(6,6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
arr_2d[2:3,1:3]

array([[13, 14]])

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [44]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [45]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [46]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
arr.max()

9

In [52]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])